### ISSUE TITLE
Download queue tab

### ISSUE THREAD

**Issue by cunidev** [solus-project/solus-sc#42] opened 2016-11-13 12:21 UTC
I think it'd be useful to have a download queue tab on the left, in order to be able to manage currently pending downloads and updates with their progress, and perhaps be able to cancel them in a more intuitive way. Nothing more than a suggestion :)

**Comment by ikeydoherty** [comment] 2017-04-20 02:24
Closing as dupe of #32

**Closed by ikeydoherty** 2017-04-20 02:24 UTC
