### ISSUE TITLE
Package list label to indicate if a package is Installed

### ISSUE THREAD

**Issue by redcollective** [solus-project/solus-sc#116] opened 2017-05-22 12:18 UTC
It would be useful if there was a label/button to indicate if a package is Installed on the package list just after the categories are selected. That way, you could see at a glance if you already had something, without needing to switch to the 'Installed' category or inspect the package details. It might sit well if aligned with the arrow indicator? If it were implemented as a button you could Install or Remove from the package list rather than the package details.

**Comment by ikeydoherty** [comment] 2017-05-22 12:49
Closing as duplicate of #45

**Closed by ikeydoherty** 2017-05-22 12:49 UTC
Labels: duplicate
